//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCharactersGame.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChineseCharactersGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 gain an immediate马到成功
        ///birds of feather.一丘之貉
        ///black sheep.害群之马
        ///break a butterfly on a wheel.小题大做
        ///cast peals before swine.明珠暗投
        ///the cat among the pigeons. 人为刀俎，我为鱼肉
        ///even a worm will turn.狗急跳墙
        ///go to the dogs.江河日下
        ///love me love my dog.爱屋及乌
        ///take a hair of the dog that bite you.以毒攻毒
        ///kill the goose that lays the golden eggs.杀鸡取卵
        ///kill two birds with one stone.一箭双雕
        ///wake a sleeping dog.惹是生非
        ///look a gift horse in the mouth.吹毛求疵
        ///neither fish nor fowl.不伦不类
        ///put/set the cart before the horse.本末倒置
        ///look like a d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ch {
            get {
                return ResourceManager.GetString("ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 春晓
        ///The pring dawn
        ///孟浩然 著(唐朝）
        ///written by Meng Haoran(Dynasty Tang)
        ///
        ///春眠不觉晓，
        ///This morn of spring in bed I&apos;m lying,
        ///处处闻啼鸟。
        ///Not to awake till birds are crying.
        ///夜来风雨声，
        ///After one night of wind and showers,
        ///花落知多少。
        ///How many are the fallen flowers!
        ///
        ///
        ///观 沧 海
        ///Gazing Out Across the Ocean
        ///曹操 著(三国）
        ///written by Cao Cao(Dynasty the Three Kingdoms)
        ///
        ///东临碣石，一观沧海。
        ///Come east of Jieshi Cliff,I gaze out across the ocean, 
        ///水何澹澹，山岛竦峙。
        ///Its rolling waves studded with rocks and islets; 
        ///树木丛生，百草丰茂。
        ///Dense the trees a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string gu {
            get {
                return ResourceManager.GetString("gu", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream huimeng1 {
            get {
                return ResourceManager.GetStream("huimeng1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream huimeng2 {
            get {
                return ResourceManager.GetStream("huimeng2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream J0214098 {
            get {
                return ResourceManager.GetStream("J0214098", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Misc_StartLevel {
            get {
                return ResourceManager.GetStream("Misc_StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a
        ///啊
        ///ā
        ///ai
        ///哎
        ///āi
        ///ang
        ///昂
        ///áng
        ///an
        ///安
        ///ān
        ///ao
        ///奥
        ///ào
        ///ba
        ///爸
        ///bà
        ///bai
        ///白
        ///bái
        ///ban
        ///班
        ///bān
        ///bang
        ///帮
        ///bāng
        ///bo
        ///波
        ///bō
        ///bu
        ///不
        ///bù
        ///bao
        ///包
        ///bāo
        ///bei
        ///被
        ///bēi
        ///ben
        ///本
        ///běn
        ///beng
        ///崩
        ///bēng
        ///bi
        ///笔
        ///bǐ
        ///bian
        ///变
        ///biàn
        ///biao
        ///表
        ///biǎo
        ///bie
        ///别
        ///bié
        ///bin
        ///宾
        ///bīn
        ///bing
        ///并
        ///bìng
        ///ca
        ///擦
        ///cā
        ///cai
        ///才
        ///cái
        ///can
        ///参
        ///cān
        ///cang
        ///仓
        ///cāng
        ///cao
        ///草
        ///cǎo
        ///ce
        ///册
        ///cè
        ///cen
        ///岑
        ///cén
        ///ceng
        ///曾
        ///céng
        ///cha
        ///茶
        ///chá
        ///chai
        ///柴
        ///chái
        ///chan
        ///产
        ///chǎn
        ///chang
        ///长
        ///cháng
        ///chao
        ///超
        ///chāo
        ///che
        ///车
        ///chē
        ///chen
        ///晨
        ///chén
        ///cheng
        ///成
        ///chéng
        ///chi
        ///吃
        ///chī
        ///chong
        ///冲
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string write {
            get {
                return ResourceManager.GetString("write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.爱屋及乌 Love me, love my dog. 
        ///2.百闻不如一见 Seeing is believing.
        ///3.比上不足比下有余 worse off than some, better off than many; to fall short of the best, but be better than the worst. 
        ///4.笨鸟先飞 A slow sparrow should make an early start. 
        ///5.不眠之夜 white night 
        ///6.不以物喜不以己悲 not pleased by external gains, not saddened by personnal losses 
        ///7.不遗余力 spare no effort; go all out; do one&apos;s best 
        ///8.不打不成交 No discord, no concord. 
        ///9.拆东墙补西墙 rob Peter to pay Paul 
        ///10.辞旧迎新 bid farewell to the old and usher in the new; ring out the o [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ya {
            get {
                return ResourceManager.GetString("ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歼 的本地化字符串。
        /// </summary>
        internal static string z1ck {
            get {
                return ResourceManager.GetString("z1ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 annihilate 的本地化字符串。
        /// </summary>
        internal static string z1ek {
            get {
                return ResourceManager.GetString("z1ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一千零一夜
        ///One Thousand and One Nights 的本地化字符串。
        /// </summary>
        internal static string zi1 {
            get {
                return ResourceManager.GetString("zi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是玉关情。
        ///Always YuGuan mood. 的本地化字符串。
        /// </summary>
        internal static string zi10 {
            get {
                return ResourceManager.GetString("zi10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国 的本地化字符串。
        /// </summary>
        internal static string zi10ck {
            get {
                return ResourceManager.GetString("zi10ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nation 的本地化字符串。
        /// </summary>
        internal static string zi10ek {
            get {
                return ResourceManager.GetString("zi10ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一月一日非今天
        ///January 1st than today 的本地化字符串。
        /// </summary>
        internal static string zi2 {
            get {
                return ResourceManager.GetString("zi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明 的本地化字符串。
        /// </summary>
        internal static string zi2ck {
            get {
                return ResourceManager.GetString("zi2ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tomorrow 的本地化字符串。
        /// </summary>
        internal static string zi2ek {
            get {
                return ResourceManager.GetString("zi2ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重点支援大西北
        ///Key support of northwest China 的本地化字符串。
        /// </summary>
        internal static string zi3 {
            get {
                return ResourceManager.GetString("zi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ͷ 的本地化字符串。
        /// </summary>
        internal static string zi3ck {
            get {
                return ResourceManager.GetString("zi3ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 head 的本地化字符串。
        /// </summary>
        internal static string zi3ek {
            get {
                return ResourceManager.GetString("zi3ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 千里挑一,百里挑一
        ///a man in a thousand,a man in a hundred 的本地化字符串。
        /// </summary>
        internal static string zi4 {
            get {
                return ResourceManager.GetString("zi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伯 的本地化字符串。
        /// </summary>
        internal static string zi4ck {
            get {
                return ResourceManager.GetString("zi4ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uncle 的本地化字符串。
        /// </summary>
        internal static string zi4ek {
            get {
                return ResourceManager.GetString("zi4ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十一个读书人
        ///eleven readers 的本地化字符串。
        /// </summary>
        internal static string zi5 {
            get {
                return ResourceManager.GetString("zi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仕 的本地化字符串。
        /// </summary>
        internal static string zi5ck {
            get {
                return ResourceManager.GetString("zi5ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 be an official 的本地化字符串。
        /// </summary>
        internal static string zi5ek {
            get {
                return ResourceManager.GetString("zi5ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下难分
        ///it is difficult to distinguish up and down 的本地化字符串。
        /// </summary>
        internal static string zi6 {
            get {
                return ResourceManager.GetString("zi6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡 的本地化字符串。
        /// </summary>
        internal static string zi6ck {
            get {
                return ResourceManager.GetString("zi6ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 card 的本地化字符串。
        /// </summary>
        internal static string zi6ek {
            get {
                return ResourceManager.GetString("zi6ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十月十日
        ///October 10th 的本地化字符串。
        /// </summary>
        internal static string zi7 {
            get {
                return ResourceManager.GetString("zi7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 萌 的本地化字符串。
        /// </summary>
        internal static string zi7ck {
            get {
                return ResourceManager.GetString("zi7ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sprout 的本地化字符串。
        /// </summary>
        internal static string zi7ek {
            get {
                return ResourceManager.GetString("zi7ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧貌换新颜
        ///Old appearance to evening 的本地化字符串。
        /// </summary>
        internal static string zi8 {
            get {
                return ResourceManager.GetString("zi8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旦 的本地化字符串。
        /// </summary>
        internal static string zi8ck {
            get {
                return ResourceManager.GetString("zi8ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dawn 的本地化字符串。
        /// </summary>
        internal static string zi8ek {
            get {
                return ResourceManager.GetString("zi8ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二十四小时。
        ///twentyfour hours 的本地化字符串。
        /// </summary>
        internal static string zi9 {
            get {
                return ResourceManager.GetString("zi9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧 的本地化字符串。
        /// </summary>
        internal static string zi9ck {
            get {
                return ResourceManager.GetString("zi9ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 old 的本地化字符串。
        /// </summary>
        internal static string zi9ek {
            get {
                return ResourceManager.GetString("zi9ek", resourceCulture);
            }
        }
    }
}
